// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Base is the predicate function for base builders.
type Base func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
